### ISSUE TITLE
Major Website Changes

### ISSUE THREAD

**Issue by SuperAuguste** [SuperAuguste/privatesuite#1]
@privatesuite/website

Hey there `website` team members! I'm working on a large patch that'll affect `privatesuitemag.com` extensively. Please express your thoughts!

Changes:
- [x] Resize Logo
- [ ] Make Menu More Dynamic
- [ ] Fix Lag
- [ ] Switch to Another Rendering Engine (pixi.js is weighing down our build, so something more lightweight that can make those cool lines would be pretty awesome!)
- [ ] Make the Homepage Cooler (more welcoming, maybe a cool introduction video and/or a big subscribe button)

**Comment by pfych** [comment]
I think we should go into more detail over "Make the Homepage Cooler" haha

**Comment by SuperAuguste** [comment]
Good idea. Edited the main Issue.
